services:
  - type: web
    name: matrix-marketplace-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_categories"
    startCommand: "gunicorn puddle.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: FRONTEND_URL
        value: https://your-frontend-domain.netlify.app
      - key: ALLOWED_HOSTS
        value: your-backend-domain.onrender.com